language: python
python:
  - "2.7"
  # - "3.3" travis-ci不支持
  # - "3.4" travis-ci不支持
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install: 
  - pip install pytest-cov
  - pip install python-coveralls==2.9.3
  - pip install coverage==4.5.4
  - pip install -r requirements.txt
# command to run tests
script: 
  - python -m pytest tests --doctest-modules --cov handlers --cov xutils --cov xauth
after_success: 
  - coveralls